/*

THIS IS A SIMPLE LADY HUNTER TIGER GAME. CHILDHOOD REFRESHED!.

IF YOU HAVE ANY SUGGESTIONS FOR IMPROVING THE GAME OR MAKING IT MORE EXCITING,
PLEASE LET ME KNOW!

THE GAME GOES LIKE THIS:
     * YOU PLAY AGAINST THE COMPUTER.
     * YOU SHOULD CHOOSE ANY ONE AMONG LADY,HUNTER AND TIGER.
     * BASICALLY LADY WILL KILL HUNTER,HUNTER WILL KILL TIGER,TIGER WILL KILL LADY
     * EVERY GAME RESULT WILL BE DISPLAYED.
     * AT THE END WHO EVER WINS MORE GAMES BETWEEN YOU AND COMPUTER,THEY WIN.

ENJOY THE GAME!

THANK YOU.

*/


#include <bits/stdc++.h>
#include <random>

using namespace std;

int getrandomnumber(int n)//random number generating function.
{
   /* srand(time(NULL));// it will take seed as input.
    return rand()%n;
    */
    
    std::random_device rd;//this will generate even non deterministic random numbers.
    
    std::mt19937 gen(rd());
    std::uniform_int_distribution<> dis(0, 100);

    // To generate a number:
    return dis(gen)%n;
}

int game(char ch1,char ch2)//the description of the game.
{
    if(ch1=='L')
     {
         if(ch2=='L')
            return 0;
            
         else if(ch2=='H')    
             return 1;
             
         else
           return -1;

     }
     
    else if(ch1=='H')
     {
          if(ch2=='L')
            return -1;
            
         else if(ch2=='H')    
             return 0;
             
         else
           return 1;

     }
     
    else
     {
          if(ch2=='L')
            return 1;
            
         else if(ch2=='H')    
             return -1;
             
         else
           return 0;

     }
       
}

int main()
{
   ios_base::sync_with_stdio(false);
   cin.tie(NULL);cout.tie(NULL);
   
   cout<<"\t\t\tWELCOME TO THE GAME MY DEAR FRIEND"<<endl<<endl;
   cout<<"THIS GAME IS CALLED \"LADY HUNTER TIGER\" "<<endl<<endl;
   int n;
   cout<<"PLEASE TELL ME HOW MANY GAMES DO YOU WANT TO PLAY? "<<endl<<endl;
   cin>>n;
   int i,p=0;
   
   char arr[3]={'L','H','T'};//this will help to convert the randomnuber to character.
   
   char chp;//character the player will select.
   char chc;// character the computer will generate.
   int playerscore=0;//will count how many games player has won.
   int compscore=0;//will count how many games computer won.
   int num=0;//will store the randomnumber generated by the computer.
   
   cout<<"OK SO LET'S BEGIN! "<<endl<<endl;
   
   for(i=0;i<n;++i)
    {
        cout<<"ENTER YOUR OPTION \"L\" FOR LADY \"H\" FOR HUNTER \"T\" FOR TIGER"<<endl;
        cin>>chp;
        num=getrandomnumber(3);//this function will return a random number in the range 0-2
        chc=arr[num];
        cout<<chp<<" vs "<<chc<<endl<<endl;
        p=game(chp,chc);
        if(p==1)
          { playerscore++;
            cout<<"WIN"<<endl;
          }
         
        else if(p==-1)
           { compscore++;
             cout<<"LOSE"<<endl;
           }
           
        else
          cout<<"DRAW"<<endl;
           
           
    }
    //game results displaying.
    cout<<"ALL THE GAMES HAVE ENDED SUCCESSFULLY "<<endl<<endl;
    cout<<"RESULTS ARE :"<<endl<<endl;
    
    if(playerscore>compscore)
     { cout<<"YOU HAVE WON "<<playerscore<<" GAMES "<<"AND COMPUTER WON "<<compscore<<" GAMES "<<endl;
      cout<<"YOU ARE THE WINNER!!!!!!";
     }
     
    else if(playerscore<compscore)
    {
        cout<<"YOU HAVE WON "<<playerscore<<" GAMES "<<"AND COMPUTER WON "<<compscore<<" GAMES "<<endl;
        cout<<"SORRY YOU ARE THE LOSER.";
    }
    
    
    else
     {
         cout<<"YOU HAVE WON "<<playerscore<<" GAMES "<<"AND COMPUTER WON "<<compscore<<" GAMES "<<endl;
         cout<<"IT IS A DRAW. TOUGH LUCK!";
     }
     
   
     return 0;
}
